### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by Zubenna** [JohannRodriguez/DungeonDicesBot-ruby-capstone#7]
Great Job, Consider the following for improvement.
- Consider using a variable to represent long text.
- Consider highlighting the features of the program in your Readme.md file
- You may need to add how to run your program in the Readme.md file.

**Comment by JohannRodriguez** [comment]
- The repeated message has been deleted and now I have only one bot message.
- The features of the project were added, also theinstructions on how to run it locally.
